//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMTLabs.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientContactsInfo
    {
        public int ClientContactId { get; set; }
        public int ClientId { get; set; }
        public int ProjectId { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public int JobTitleLookupId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Lookup Lookup { get; set; }
        public virtual Project Project { get; set; }
    }
}
