//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMTLabs.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyFieldReport
    {
        public int DFRId { get; set; }
        public int ProjectId { get; set; }
        public int ClientId { get; set; }
        public int WorkOrderId { get; set; }
        public string ReportNumber { get; set; }
        public int WeatherConditionLookupId { get; set; }
        public string Summary { get; set; }
        public int TimeRecordId { get; set; }
        public int EmpId { get; set; }
        public string PerosnInformedName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Lookup Lookup { get; set; }
        public virtual Project Project { get; set; }
        public virtual TimeRecord TimeRecord { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
