//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMTLabs.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Logout_Logs
    {
        public int LogId { get; set; }
        public string UserName { get; set; }
        public bool ValidAttempt { get; set; }
        public string IPAddress { get; set; }
        public int DescriptionLookupId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Lookup Lookup { get; set; }
    }
}
