//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMTLabs.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoilMaterial
    {
        public int SoilMaterialId { get; set; }
        public int ProjectId { get; set; }
        public string MaterialNumber { get; set; }
        public string MaterialDescription { get; set; }
        public decimal SpecifiedCompaction { get; set; }
        public decimal SpecifiedMoisture { get; set; }
        public int TestMethodLookupId { get; set; }
        public int LL { get; set; }
        public int PL { get; set; }
        public int PI { get; set; }
        public decimal MaxDryDensity { get; set; }
        public decimal OptimumMoisture { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Lookup Lookup { get; set; }
        public virtual Project Project { get; set; }
    }
}
