//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMTLabs.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeRecord()
        {
            this.DailyFieldReports = new HashSet<DailyFieldReport>();
        }
    
        public int TimeRecordId { get; set; }
        public System.TimeSpan TimeDepartOffice { get; set; }
        public System.TimeSpan TimeArriveProject { get; set; }
        public System.TimeSpan TimeDepartProject { get; set; }
        public System.TimeSpan TimeArriveOffice { get; set; }
        public Nullable<decimal> Lunch { get; set; }
        public decimal TotalTime { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyFieldReport> DailyFieldReports { get; set; }
    }
}
